import type { StoryboardScene } from "@/app/actions/storyboard";

export function generateShotList(
  scenes: StoryboardScene[],
  projectTitle: string = "Untitled Cinema Sequence"
): string {
  const totalDuration = scenes.reduce((acc, s) => acc + (s.durationSeconds || 5), 0);
  const now = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let output = `# ${projectTitle.toUpperCase()}\n`;
  output += `**Production Master Shot List & Directing Breakdown**\n`;
  output += `- **Date**: ${now}\n`;
  output += `- **Total Scenes**: ${scenes.length}\n`;
  output += `- **Total Sequence Runtime**: ${totalDuration} seconds (~${(totalDuration / 60).toFixed(1)} mins)\n`;
  output += `- **Generated by**: TryElusk Studio Cinema Suite\n\n`;

  output += `| Scene | Title / Shot Type | Duration | Format | Dialogue / Audio | Production Prompt |\n`;
  output += `| :---: | :--- | :---: | :---: | :---: | :--- |\n`;

  scenes.forEach((scene, idx) => {
    const sceneNum = String(idx + 1).padStart(2, "0");
    const title = scene.title || `Scene ${idx + 1}`;
    const dur = `${scene.durationSeconds || 5}s`;
    const format = scene.mediaType.toUpperCase();
    const audio = scene.audioUrl ? "✓ Linked Dialogue" : "—";
    const prompt = (scene.prompt || "").replace(/\|/g, "/").replace(/\r?\n/g, " ");

    output += `| **#${sceneNum}** | ${title} | ${dur} | ${format} | ${audio} | ${prompt} |\n`;
  });

  output += `\n---\n\n`;
  output += `### Scene Media Assets & Source URLs\n\n`;
  scenes.forEach((scene, idx) => {
    output += `**Scene ${idx + 1}: ${scene.title}**\n`;
    output += `- Media URL: ${scene.mediaUrl || "Pending take render"}\n`;
    if (scene.audioUrl) {
      output += `- Audio URL: ${scene.audioUrl}\n`;
    }
    output += `- Prompt: \`${scene.prompt}\`\n\n`;
  });

  return output;
}
