import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { CreditProvider } from "@/context/credit-context";
import { RenderJobProvider } from "@/context/render-job-context";
import { RenderCompletionToast } from "@/components/shared/render-completion-toast";
import { createClient } from "@/lib/supabase/server";
import { getUserBalance } from "@/lib/wallet/wallet";

import { ProjectProvider } from "@/context/project-context";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "TryElusk — Turn your idea into a movie",
  description:
    "AI-powered filmmaking platform. Describe a scene in plain English and get cinematic video and images generated by AI.",
  icons: {
    icon: [{ url: "/tryelusk-favicon.svg", type: "image/svg+xml" }],
    shortcut: ["/tryelusk-favicon.svg"],
    apple: ["/tryelusk-favicon.svg"],
  },
};

import { MobileBottomBar } from "@/components/layout/mobile-bottom-bar";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  let initialBalance = 0;
  if (user) {
    initialBalance = await getUserBalance(user.id);
  }

  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/tryelusk-favicon.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${inter.variable} min-h-screen bg-[#0B0B0F] text-[#F2F2F5] font-sans antialiased selection:bg-[#7C5CFF]/30 selection:text-white`}
      >
        <CreditProvider initialBalance={initialBalance}>
          <ProjectProvider>
            <RenderJobProvider>
              <div className="relative flex min-h-screen flex-col pb-16 md:pb-0">
                <Header />
                <main className="flex-1">{children}</main>
                <RenderCompletionToast />
                <MobileBottomBar />
              </div>
            </RenderJobProvider>
          </ProjectProvider>
        </CreditProvider>
      </body>
    </html>
  );
}
